version: '3.5'

volumes:
  trustanchors:
  cabundle:

services:

  trust:
    image: indigoiam/egi-trustanchors
    environment:
      - FORCE_TRUST_ANCHORS_UPDATE=1
    volumes:
      - trustanchors:/etc/grid-security/certificates
      - cabundle:/etc/pki

  ts:
    image: andreaceccanti/wlcg-jwt-compliance-tests

    environment:
      - TZ=Europe/Rome
      - REQUESTS_CA_BUNDLE=/etc/pki/tls/cert.pem
      - OIDC_AGENT_SECRET

    volumes:
      - cabundle:/etc/pki
      - trustanchors:/etc/grid-security/certificates
      - ./assets/.config/oidc-agent:/home/test/.config/oidc-agent:ro
      - .:/home/test/test-suite

    entrypoint: /tini -- sleep infinity

    extra_hosts:
      - "storm.example: 192.168.65.2"
