name: Run JWT compliance testsuite

on:
  push:
    branches: [ master ]
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Fetch crls
        run: docker-compose up trust

      - name: Start testsuite
        run: 
          - docker-compose up -d ts 
          - docker-compose exec ts bash -c 'cd test-suite && sh ci/run.sh'
          - docker-compose down

