name: Run JWT compliance testsuite

on:
  push:
    branches: [ master ]
jobs:

  run-testsuite:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Fetch crls
        run: docker-compose up trust

      - name: Start testsuite
        env:
          OIDC_AGENT_SECRET: ${{ secrets.OIDC_AGENT_SECRET }}
        run: |
          docker-compose up -d ts 
          docker-compose exec -T ts bash -c 'cd test-suite && sh ci/run.sh'
          docker-compose down
