name: Run JWT compliance testsuite

on:
  push:
    branches: [ master ]
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Fetch crls
        run: docker-compose up trust

